### PR TITLE
Miscellaneous: GEDI L4A Subsetting Example

### PR DESCRIPTION
**Pull request by jjfrench**
[#236](https://github.com/NASA-IMPACT/active-maap-sprint/issues/236) GEDI Subset Simpler Example

Miscellaneous:
- Added GEDI_L4A_Subsetting.ipynb

### CODE REVIEW

**Comment by jjfrench** [comment]
Linking https://github.com/NASA-IMPACT/active-maap-sprint/issues/231, https://github.com/NASA-IMPACT/active-maap-sprint/issues/232

**Review by chuckwondo — CHANGES_REQUESTED** [review]
Great start! I began to add some comments, but some things are a bit involved to explain via comments, so I'm going to schedule time for us to huddle over Slack to go over the details. After that, you should be able to address change requests. This should help us reduce back-and-forth via comments.

**Comment by jjfrench** [comment]
I really liked the use of the xml response for job status and a lot of nice clean up! What are your thoughts on adding back in max_value to the backoff decorator? It was a little disconcerting seeing the backoff for 7+ minutes when I ran one of my aoi's. Other than that, everything else looked like major improvements for the user 👍

**Review by chuckwondo — APPROVED** [review]
Looks good!

**Pull request merged**
