### PR TITLE
Science data use case estimates

### PR DESCRIPTION
**Pull request by slesaad**
This PR adds the files and the notebook with code that estimates the total data files/granules and their sizes for each of the MAAP science use case.

### CODE REVIEW

**Comment by wildintellect** [comment]
@slesaad please comment the code explaining what each function does and how to run the overall sequence to get totals.

**Comment by slesaad** [comment]
@wildintellect does it look good now?

**Comment by wildintellect** [comment]
@slesaad the code is now decently commented, but we need Markdown at the top and/or a Readme in the folder that explains the purpose of the code and how to use it.

**Comment by slesaad** [comment]
@wildintellect I've added some text. See if that's enough. If not, I might need some help with what specific information we want to add.

**Review by wildintellect — APPROVED** [review]
Looks good. We can iterate on the documentation as we get more questions.

**Pull request merged**
